kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
    name: azure-disk
provisioner: kubernetes.io/azure-disk
parameters:
    storageaccounttype: Standard_LRS
    kind: Managed
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: mssql-data
    annotations:
        volume.beta.kubernetes.io/storage-class: azure-disk
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 8Gi
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: mssql-deployment
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: mssql
        spec:
            terminationGracePeriodSeconds: 10
            containers:
                - name: mssql
                  image: thhtalks.azurecr.io/sql:latest
                  ports:
                      - containerPort: 1433
                  env:
                      - name: ACCEPT_EULA
                        value: 'Y'
                      - name: SA_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: mssql
                                key: SA_PASSWORD
                  volumeMounts:
                      - name: mssqldb
                        mountPath: /var/opt/mssql
            volumes:
                - name: mssqldb
                  persistentVolumeClaim:
                      claimName: mssql-data
---
apiVersion: v1
kind: Service
metadata:
    name: mssql-deployment
spec:
    selector:
        app: mssql
    ports:
        - protocol: TCP
          port: 1433
          targetPort: 1433
    type: LoadBalancer
